services:
  web:
    build: .
    container_name: django_app
    command: sh wait-for-db.sh
    volumes:
      - .:/app
    ports:
      - "8001:8000" # a porta do servidor 
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: nome_do_seu_db # nome do seu banco de dados MySQL
      MYSQL_USER: seu_user  # nome do seu User Mysql
      MYSQL_PASSWORD: sua_senha # a senha do banco de dado MySQL
      MYSQL_ROOT_PASSWORD: root # deixe root
    ports:
      - "3306:3306" # A mesma porta de settings_db 