# Generated by Django 6.0.3 on 2026-03-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cover_url_usergamelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='igbd_id',
            new_name='igdb_id',
        ),
    ]
