# Generated by Django 6.0.3 on 2026-03-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_igbd_id_game_igdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergamelist',
            name='user',
        ),
        migrations.AddField(
            model_name='usergamelist',
            name='user_token',
            field=models.CharField(default=1002103013010, max_length=100),
            preserve_default=False,
        ),
    ]
